
# Plot params
fig_path: "../paper_figures/"
fig_width: 6.85 # inches
panel_fontsize: 12
legend_fontsize: 8
annotation_fontsize: 7.5

# Colors all
c_sim: "k"
c_h1: "c"
c_h2: "y"
c_h3: "m"
c_noise: "darkgray"
c_real: "purple"
c_low: "deepskyblue"
c_med: "limegreen"
c_high: "#ff7f00"
c_ground: "grey"
c_error: "r"
c_range1: "b"
c_range2: "g"
c_range3: "y"
c_ap: "grey"
c_pre: "c"
c_seiz: "r"
c_post: "y"

# Colors 1
c_aperiodic: "#ff7f00"
c_osc: "#4daf4a"
c_fit: "#377eb8"
c_thresh: "#999999"
c_flat: "#f781bf"
c_box: [.9, .9, .9]

# Colors 2 a)
c_fits: ["limegreen", "r", "r", "r"]

# Colors 3 b)
c_fit_fooof1: "purple"
c_fit_fooof2: "c"
c_fit_fooof3: "lime"
c_fit_fooof4: "orange"

# Colors 5
c_fooof: "deepskyblue"
h_colors: ["g", "C1", "orangered"]

# Colors 6 Supp
c_ap_real1: "C1"
c_ap_real2: "C2"

# Colors 8
c_fit_straight: "r--"
c_fit_fooof: "b--"
c_fit_irasa: "g--"